# Generated by Django 5.0.6 on 2024-07-01 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sinopsis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_temporada', models.PositiveIntegerField()),
                ('numero_episodio', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='series.serie')),
            ],
        ),
    ]
