# Generated by Django 5.0.6 on 2024-07-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitulo',
            name='numero_episodio',
        ),
        migrations.RemoveField(
            model_name='capitulo',
            name='numero_temporada',
        ),
        migrations.AddField(
            model_name='capitulo',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capitulo',
            name='temporada',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
