# Generated by Django 5.0.6 on 2024-07-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_remove_capitulo_numero_episodio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/img_series/'),
        ),
    ]
