# Generated by Django 5.0.6 on 2024-07-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_serie_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/series/'),
        ),
    ]
