# Generated by Django 5.0.6 on 2024-07-01 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('series', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('puntuacion', models.PositiveIntegerField()),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='series.capitulo')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='series.serie')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
