# Generated by Django 5.0.6 on 2024-07-02 02:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseñas', '0001_initial'),
        ('series', '0002_remove_capitulo_numero_episodio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='capitulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.capitulo'),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='puntuacion',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.serie'),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
